#ifndef VN_FRACTAL_H
#define VN_FRACTAL_H

#ifndef UGC_COMPILER
#include <cstdint>
#endif

namespace vn {

// Fractal scale levels
enum class FractalScale : uint32_t {
  Entity = 0,      // Entity level (rocks, creatures, drones)
  Server = 1,      // Server level (computational entities)
  Federation = 2    // Federation level (server networks)
};

// Fractal annotation for functions and types
// Used by [[fractal]] attribute
struct FractalAnnotation {
  FractalScale scale;
  const char* name;  // Function/type name at this scale

  FractalAnnotation(FractalScale s, const char* n) : scale(s), name(n) {}
};

// Helper to generate scale-specific function names
// e.g., "update_pillars" becomes "update_pillars_entity", etc.
inline const char* getFractalFunctionName(const char* base, FractalScale scale) {
  switch (scale) {
    case FractalScale::Entity:     return "entity";
    case FractalScale::Server:     return "server";
    case FractalScale::Federation: return "federation";
    default: return "unknown";
  }
}

// Template for fractal functions
// Compiler generates 3 versions of the function
template<typename T>
struct FractalFunction {
  // Entity scale version
  static void entity_version(T& obj) {
    // Generated by compiler
  }

  // Server scale version
  static void server_version(T& obj) {
    // Generated by compiler
  }

  // Federation scale version
  static void federation_version(T& obj) {
    // Generated by compiler
  }
};

} // namespace vn

#endif // VN_FRACTAL_H
